//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovieEntity()
        {
            this.ActorEntities = new HashSet<ActorEntity>();
        }
    
        public int Movie_Id { get; set; }
        public int Producer_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Movie_Year { get; set; }
        public string Movie_Plot { get; set; }
        public byte[] Movie_Poster { get; set; }
    
        public virtual ProducerEntity ProducerEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActorEntity> ActorEntities { get; set; }
    }
}
